### ISSUE TITLE
does warp mixed support --range option

### ISSUE THREAD

**Issue by lddlww** [minio/warp#206] opened 2022-02-14 02:09 UTC
does ```warp mixed```  support ```--range``` option like ```warp get```?

i want to get ```32KB``` length from ```32GB``` object in ```mixed``` benchmark

**Comment by harshavardhana** [comment] 2022-09-09 21:26
feel free to send a PR @lddlww

**Comment by harshavardhana** [comment] 2022-09-09 21:28
closing as duplicate of #204

**Closed by harshavardhana** 2022-09-09 21:28 UTC
Labels: good first issue
