### ISSUE TITLE
warp.exe: <ERROR> delimiter must be a one-character string

### ISSUE THREAD

**Issue by kwit75** [minio/warp#198] opened 2021-11-30 18:15 UTC
just got this when running:

warp get --host=s3.us-west-002.xxx.com --access-key=XXXX --secret-key=XXXXX --tls=true --bucket=test-benchmark --autoterm --benchdata=./benchmark.csv

tried from Ubuntu (bin and docker) and Windows (bin/docker). Same issue.

**Comment by austinpena-taloflow** [comment] 2021-11-30 18:22
This error stopped the benchmark data from being written FYI

**Comment by austinpena-taloflow** [comment] 2021-11-30 18:32
It also happened when testing Backblaze B2. Perhaps they're missing part of the S3 API that causes this?

**Comment by klauspost** [comment] 2021-11-30 19:11
@austinpena-taloflow When you write "It also happened " does that mean it only happened on B2 or that it also happens on S3/MinIO servers?

**Comment by klauspost** [comment] 2021-11-30 19:15
I am pretty sure we only use `/` as delimiter.

**Comment by kwit75** [comment] 2021-11-30 19:28
the --secret parameter has '/' symbol inside of the password string. Could it be an issue? should I escape it somehow?

**Comment by harshavardhana** [comment] 2021-11-30 20:47
> the --secret parameter has '/' symbol inside of the password string. Could it be an issue? should I escape it somehow?

This looks like an implementation issue perhaps some parsing issue with B2

**Comment by klauspost** [comment] 2021-12-01 11:51
@kwit75 @austinpena-taloflow  Please provide useful information, what are you running (commandline), against which hosts, what is the exact output?

With just an error message that AFAICT doesn't come from warp itself, but from the remote host, there is nothing I can do.

**Comment by austinpena-taloflow** [comment] 2021-12-01 14:27
@kwit75 Will shed more light on it, but the issue doesn't stop the benchmark from running, only the CSV from being produced.
> When you write "It also happened " does that mean it only happened on B2 or that it also happens on S3/MinIO servers?

The benchmark ran without issues on B2. On S3 it works. 

>This looks like an implementation issue perhaps some parsing issue with B2

The test gets run, but the CSV had an issue. Can you expand on what happened with the CSV @kwit75?

**Comment by klauspost** [comment] 2021-12-01 16:39
Testing on Windows I don't see any issues with what you provide:
```
λ warp put --duration=10s --obj.size=1K --host=127.0.0.1:{9001...9002} --access-key=minio --secret-key=minio/123 --benchdata=./benchmark.csv
warp: Benchmark data written to "./benchmark.csv.csv.zst"
[...]
```

**Comment by harshavardhana** [comment] 2021-12-01 17:00
@klauspost this issue is B2 related unrelated to the tool - B2 is failing Listing() during cleanup.

**Comment by klauspost** [comment] 2021-12-01 17:04
@harshavardhana It is still a bit up in the air what the problem is

> The benchmark ran without issues on B2. On S3 it works.

So still not sure what the issue it. The error does indicate a serverside problem.

**Comment by harshavardhana** [comment] 2021-12-01 17:24
> So still not sure what the issue it. The error does indicate a serverside problem.

The error actually happens at the end of the run @klauspost mostly during cleanup.  The error is an error returned by ListObjects when `delimiter=two-characters`

**Comment by harshavardhana** [comment] 2021-12-01 17:26
However this is not a requirement in AWS S3 to have `delimiter=<more-than-one-character>`

**Comment by klauspost** [comment] 2021-12-02 16:36
But we don't send 2 character delimiters. We don't even send one for the [ListObjects](https://github.com/minio/warp/blob/b8830bc9cdf30ea616106da117696b4ead51592f/pkg/bench/benchmark.go#L186) call.

Either way, this is pointless without any info. Closing.

**Closed by klauspost** 2021-12-02 16:36 UTC
