### ISSUE TITLE
warp worker needs to listen on all IP addresses

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/warp#62] opened 2020-02-08 01:33 UTC
Currently warp listens only on localhost:
```
krishna@escape:~$ warp client
warp: Listening on 127.0.0.1:7761
```

It should listen on all the IPs.

**Comment by harshavardhana** [comment] 2020-02-08 01:36
Closing as duplicate of #47

**Closed by harshavardhana** 2020-02-08 01:36 UTC
